services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: quiz_db
      MYSQL_USER: quiz_user
      MYSQL_PASSWORD: quiz_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - DATABASE_URL=mysql://quiz_user:quiz_password@db:3306/quiz_db
      - NEXTAUTH_URL=http://stomtest.nsmu.ru
      - NEXTAUTH_SECRET=your_nextauth_secret
      - PORT=5173
      - HOSTNAME=0.0.0.0
    depends_on:
      - db
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  mariadb_data:
